{
 "title": "CTC Rack Overview",
 "description": "Temperature and Power consumption by Rack",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 26, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Avg. Inlet Ambient Temperature",
   "type": "gauge",
   "description": "Sorted by Rack",
   "gridPos": { "h": 12, "w": 12, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(rack) (ilorest_node{metricdetail=\"01-Inlet Ambient\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Power Consumption",
   "type": "bargauge",
   "description": "Sorted by Rack",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rack) (ilorest_node{metricdetail=\"Average\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(ilorest_node{metricdetail=\"Average\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average Ambient Inlet Temperature",
   "type": "timeseries",
   "description": "Average of all nodes in a rack. ",
   "gridPos": { "h": 14, "w": 12, "x": 2, "y": 12 },
   "targets": [
    {
     "expr": "avg by(rack) (ilorest_node{nodemetric=\"Temperature\", metricdetail=\"01-Inlet Ambient\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Power Consumption",
   "type": "bargauge",
   "description": "Sorted by Rack",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rack) (ilorest_node{metricdetail=\"Maximum\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(ilorest_node{metricdetail=\"Maximum\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}