{
 "title": "Power Consumption",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 25, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Power State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"State\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Average ",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "SUM(ilorest_node{metricdetail=\"Average\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "ilorest_node{metricdetail=\"Average\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "SUM(ilorest_node{metricdetail=\"Maximum\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "ilorest_node{metricdetail=\"Maximum\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}