{
 "title": "Temperature Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 25, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "01-Inlet Ambient",
   "type": "bargauge",
   "gridPos": { "h": 25, "w": 7, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"01-Inlet Ambient\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "02-CPU 1",
   "type": "bargauge",
   "gridPos": { "h": 25, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"02-CPU 1\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "03-CPU 2",
   "type": "bargauge",
   "gridPos": { "h": 25, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"03-CPU 2\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}