{
 "title": "Temperature Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "gridPos": { "h": 25, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Inlet Ambient Temperature",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 21, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"01-Inlet Ambient\"}   ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "01-Inlet Ambient",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"01-Inlet Ambient\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "54-P/S 1 Inlet",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"54-P/S 1 Inlet\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "55-P/S 2 Inlet",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilorest_node{metricdetail=\"55-P/S 2 Inlet\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}